using System;
using System.CodeDom;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GameLibraryDBClient.Constants
{
    static class Procedures
    {
        public const string ADDAUTHOR = "TWORCY_PACKAGE.ADDAUTHOR";

        public const string ADDGAME = "GRY_PACKAGE.ADDGAME";

        public const string ADDGAMEGENRE = "GRY_GATUNKI_PACKAGE.ADDGAMEGENRE";

        public const string ADDGENRE = "GATUNKI_PACKAGE.ADDGENRE";

        public const string ADDPUBLISHER = "WYDAWCY_PACKAGE.ADDPUBLISHER";

        public const string ADDREVIEW = "RECENZJE_PACKAGE.ADDREVIEW";

        public const string REMOVEAUTHOR = "TWORCY_PACKAGE.REMOVEAUTHOR";

        public const string REMOVEGAME = "GRY_PACKAGE.REMOVEGAME";

        public const string REMOVEGAMEGENRE = "GRY_GATUNKI_PACKAGE.REMOVEGAMEGENRE";

        public const string REMOVEGENRE = "GATUNKI_PACKAGE.REMOVEGENRE";

        public const string REMOVEPUBLISHER = "WYDAWCY_PACKAGE.REMOVEPUBLISHER";

        public const string REMOVEREVIEW = "RECENZJE_PACKAGE.REMOVEREVIEW";

        public const string UPDATEAUTHOR = "TWORCY_PACKAGE.UPDATEAUTHOR";

        public const string UPDATEGAME = "GRY_PACKAGE.UPDATEGAME";

        public const string UPDATEGAMEGENREBYGAMEID = "GRY_GATUNKI_PACKAGE.UPDATEGAMEGENREBYGAMEID";

        public const string UPDATEGENRE = "GATUNKI_PACKAGE.UPDATEGENRE";

        public const string UPDATEPUBLISHER = "WYDAWCY_PACKAGE.UPDATEPUBLISHER";

        public const string UPDATEREVIEW = "RECENZJE_PACKAGE.UPDATEREVIEW";

        public const string UPDATEGAMEPRICEBASEDONMONTHLYSALES = "UPDATEGAMEPRICEBASEDONMONTHLYSALES";
    }
    
    static class Functions
    {
        public const string GETALLAUTHORS = "TWORCY_PACKAGE.GETALLAUTHORS";

        public const string GETALLGAMEGENRESNAMES = "GRY_GATUNKI_PACKAGE.GETALLGAMEGENRESNAMES";

        public const string GETALLGAMES = "GRY_PACKAGE.GETALLGAMES";
        
        public const string GETALLGENRES = "GATUNKI_PACKAGE.GETALLGENRES";
        
        public const string GETALLPUBLISHERS = "WYDAWCY_PACKAGE.GETALLPUBLISHERS";
        
        public const string GETALLREVIEWS = "RECENZJE_PACKAGE.GETALLREVIEWS";
        
        public const string GETAVERAGEGAMERATING = "GRY_PACKAGE.GETAVERAGEGAMERATING";
        
        public const string GETAVERAGERATINGBYAUTHOR = "TWORCY_PACKAGE.GETAVERAGERATINGBYAUTHOR";
        
        public const string GETBESTEARNINGGAMEBYAUTHOR = "TWORCY_PACKAGE.GETBESTEARNINGGAMEBYAUTHOR";
        
        public const string GETBESTEARNINGGENREBYAUTHOR = "TWORCY_PACKAGE.GETBESTEARNINGGENREBYAUTHOR";
        
        public const string GETBESTRATEDGAME = "GRY_PACKAGE.GETBESTRATEDGAME";
        
        public const string GETBESTRATEDGAMEFORAUTHOR = "TWORCY_PACKAGE.GETBESTRATEDGAMEFORAUTHOR";
        
        public const string GETBESTRATEDGAMEFORPUBLISHER = "WYDAWCY_PACKAGE.GETBESTRATEDGAMEFORPUBLISHER";
        
        public const string GETBESTRATEDGENREFORPUBLISHER = "WYDAWCY_PACKAGE.GETBESTRATEDGENREFORPUBLISHER";
        
        public const string GETBESTSELLINGGAMEFORPUBLISHER = "WYDAWCY_PACKAGE.GETBESTSELLINGGAMEFORPUBLISHER";
        
        public const string GETBESTSELLINGGENREFORPUBLISHER = "WYDAWCY_PACKAGE.GETBESTSELLINGGENREFORPUBLISHER";
        
        public const string GETGAMECREATORNAME = "GRY_PACKAGE.GETGAMECREATORNAME";
        
        public const string GETGAMEGENRES = "GRY_PACKAGE.GETGAMEGENRES";
        
        public const string GETGAMEPUBLISHERNAME = "GRY_PACKAGE.GETGAMEPUBLISHERNAME";
        
        public const string GETGAMEREVIEWS = "GRY_PACKAGE.GETGAMEREVIEWS";
        
        public const string GETGAMESANDEARNINGSBYAUTHOR = "GRY_PACKAGE.GETGAMESANDEARNINGSBYAUTHOR";
        
        public const string GETGAMESBYAUTHOR = "TWORCY_PACKAGE.GETGAMESBYAUTHOR";
                
        public const string GETGAMESBYGENRE = "GATUNKI_PACKAGE.GETGAMESBYGENRE";
        
        public const string GETGENRESWITHEARNINGSANDAVGRATINGSBYAUTHOR = "TWORCY_PACKAGE.GETGENRESWITHEARNINGSANDAVGRATINGSBYAUTHOR";

        public const string GETHIGHESTEARNINGGAME = "GRY_PACKAGE.GETHIGHESTEARNINGGAME";
           
        public const string GETTOTALREVENUE = "GRY_PACKAGE.GETTOTALREVENUE";

        public const string GETBESTEARNIGAUTHOR = "TWORCY_PACKAGE.GETBESTEARNINGAUTHOR";

        public const string GETBESTRATEDAUTHOR = "TWORCY_PACKAGE.GETBESTRATEDAUTHOR";

        public const string GETBESTEARNINGPUBLISHER = "WYDAWCY_PACKAGE.GETBESTEARNINGPUBLISHER";

        public const string GETBESTRATEDPUBLISHER = "WYDAWCY_PACKAGE.GETBESTRATEDPUBLISHER";

        public const string GETAVERAGERATINGBYPUBLISHER = "WYDAWCY_PACKAGE.GETAVERAGERATINGBYPUBLISHER";

        public const string GETGENRESWITHRATINGSANDEARNINGSBYPUBLISHER = "WYDAWCY_PACKAGE.GETGENRESWITHRATINGSANDEARNINGSBYPUBLISHER";

        public const string GETALLGAMESBYPUBLISHER = "WYDAWCY_PACKAGE.GETALLGAMESBYPUBLISHER";

        public const string GETBESTRATEDGENRE = "GATUNKI_PACKAGE.GETBESTRATEDGENRE";

        public const string GETBESTEARNINGGENRE = "GATUNKI_PACKAGE.GETBESTEARNINGGENRE";

        public const string GETAVERAGERATINGBYGENRE = "GATUNKI_PACKAGE.GETAVERAGERATINGBYGENRE";

        public const string GETTOTALEARNINGSBYGENRE = "GATUNKI_PACKAGE.GETTOTALEARNINGSBYGENRE";

        public const string GETGAMENAMEBYID = "GRY_GATUNKI_PACKAGE.GETGAMENAMEBYID";

        public const string GETGENRENAMEBYID = "GRY_GATUNKI_PACKAGE.GETGENRENAMEBYID";
    }
}